config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  
  get 'topics/index'

  get 'topics/show'

  devise_for :users, path: '',path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'tech-news', to: 'pages#tech_news'
  
  resources :blogs do
    member do 
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies, 
                                    allow_destroy: true,
                                    reject_if: lambda { |attrs| attrs['name'].blank? }
    
    validates_presence_of :title, :body
    
    mount_uploader :main_image, PortfolioUploader
    mount_uploader :thumb_image, PortfolioUploader
    
    
    def self.angular
        where(subtitle: 'Angular')
    end
    
    def self.by_position
        order("position ASC")
    end
    
    scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }
end
  

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
   access all: [:show, :index, :angular], user: {except: [:destroy, :edit, :create, :new, :update, :sort]}, site_admin: :all
  layout "blog"
  layout 'portfolio'
  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.by_position
  end
  
  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    
    render nothing: true
  end
  def angular
    @angular_portfolio_items = Portfolio.angular
  end
  
  def show
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
    
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolio_show_path(@portfolio), notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolio_show_path(@portfolio), notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:title, 
                                        :subtitle,
                                        :body,
                                        :main_image,
                                        :thumb_image,
                                        technologies_attributes: [:id, :name, :_destroy]
                                        )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
    def login_helper style = ''
        if current_user.is_a?(GuestUser)
            (link_to "Register", new_user_registration_path, class: style) + 
                " ".html_safe +
            (link_to "Login", new_user_session_path, class: style)
        else
            link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?'}, class: style 
        end 
    end
    
    def image_generator(height:, width:)
        "http://placehold.it/#{height}x#{width}"
    end
     
     
     
    def portfolio_img img, type
        if img.model.main_image? || img.model.thumb_image?
          img
        elsif type == 'thumb'
          image_generator(height: '350', width: '200')
        elsif type == 'main'
          image_generator(height: '600', width: '400')
        end
    end
    
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio) do |f| %>
  <% if portfolio.errors.any? %>
     <% portfolio.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
  
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field :main_image, style: 'display:none;' %>
        </label>
        
      </div>
      
      <div class="form-group">
         <label class="btn btn-primary">
          Upload a thumb image file <%= f.file_field :thumb_image,style: 'display:none;' %>
        </label>
      </div>
      
      
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: 13%>
      </div>
    </div>
  </div>
  <hr>
  <div class="col-md-12">
    <h2>Technology Used</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
    </div>  
    
    <div>
      <%= link_to_add_association 'Add Technology', f, :technologies %>
    </div>
  
    <div class="form-group">
      <%= f.submit "Save Portfolio Item", class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div class="col-md-4">
        <div class="card" data-id="<%= portfolio.id %>">
                <%= image_tag portfolio_img(portfolio.thumb_image, "thumb"), width: '100%' %>
                <p class="card-text">
                        <span><%= link_to portfolio.title, portfolio_show_path(portfolio) %></span>
                        <%= portfolio.subtitle %>
                </p>
        </div>
        
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<p id="notice"><%= notice %></p>

<h1>Portfolios</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Body</th>
      <th>Main iamge</th>
      <th>Thumb image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @angular_portfolio_items.each do |portfolio| %>
      <tr>
        <td><%= link_to portfolio.title, portfolio_show_path(portfolio.id) %></td>
        <td><%= portfolio.subtitle %></td>
        <td><%= portfolio.body %></td>
        <td><%= image_tag portfolio.main_image unless portfolio.main_image.nil? %></td>
        <td><%= image_tag portfolio.thumb_image unless portfolio.thumb_image %></td>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio)  if logged_in?(:site_admin)%></td>
        <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_portfolio_path if logged_in?(:site_admin) %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
    <h1>Editing Portfolio</h1>
    
    <%= render 'form', portfolio: @portfolio %>
  
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <%= source_helper("alert alert-warning") %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>" >
        <%= render @portfolios %>
    </div>
      <!--<%= link_to 'New Portfolio', new_portfolio_path if logged_in?(:site_admin) %>-->
    
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
    <h1>Create Portfolio</h1>
        <%= render 'form', portfolio: @portfolio %>  
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio.main_image, "main"), width: '100%'%>
    </div>
    
    <div class="col-md-5">
      
      <h1>
        <%= @portfolio.title %>
      </h1>
      
      <em>
        <%= @portfolio.subtitle %>
      </em>
      
      <p>
        <%= @portfolio.body %>
      </p>
      
      <hr>
      <H2>Technologies Used:</H2>
      <% @portfolio.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>
      
      <% if logged_in?(:site_admin) %>
      <div>
        <%= link_to "Edit Item", edit_portfolio_path(@portfolio), class: 'btn btn-warning' %>
      </div>
      <% end %>
    </div>
  </div>
</div>